export const noticiasMock = [
  // Dia dos Namorados
  {
    id: 1,
    titulo: 'Comércio aposta em promoções para o Dia dos Namorados',
    descricao: 'Lojas investem em descontos e campanhas para atrair casais na data comemorativa.',
    data: '2024-06-12',
    fonte: 'Jornal do Brasil',
    texto: 'O comércio brasileiro está otimista com as vendas para o Dia dos Namorados, apostando em promoções e facilidades de pagamento para atrair consumidores.',
    empresas_citadas: ['Magazine Luiza', 'Americanas'],
    sentimento: 'positivo',
    assuntos: ['comércio', 'promoções', 'data comemorativa'],
    impressoes: 12000,
    valoracao: 35000.50
  },
  {
    id: 2,
    titulo: 'Casais compartilham histórias marcantes no Dia dos Namorados',
    descricao: 'Redes sociais são palco de declarações e surpresas.',
    data: '2024-06-12',
    fonte: 'O Globo',
    texto: 'Milhares de casais usaram as redes sociais para compartilhar momentos especiais nesta data.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['relacionamento', 'redes sociais', 'amor'],
    impressoes: 8000,
    valoracao: 18000.00
  },
  {
    id: 3,
    titulo: 'Vendas de flores crescem 20% no Dia dos Namorados',
    descricao: 'Floristas comemoram aumento nas vendas em relação ao ano passado.',
    data: '2024-06-12',
    fonte: 'Folha de S.Paulo',
    texto: 'O setor de floricultura registrou crescimento expressivo nas vendas para a data.',
    empresas_citadas: ['Floricultura Rosa Linda'],
    sentimento: 'positivo',
    assuntos: ['flores', 'vendas', 'comércio'],
    impressoes: 5000,
    valoracao: 9000.00
  },
  {
    id: 4,
    titulo: 'Restaurantes lotam no jantar do Dia dos Namorados',
    descricao: 'Reservas antecipadas garantem mesas para casais.',
    data: '2024-06-12',
    fonte: 'Estadão',
    texto: 'Restaurantes de todo o país registraram alta procura para o jantar especial.',
    empresas_citadas: ['Restaurante Bella Noite'],
    sentimento: 'positivo',
    assuntos: ['restaurantes', 'jantar', 'reservas'],
    impressoes: 7000,
    valoracao: 12000.00
  },
  {
    id: 5,
    titulo: 'Campanhas publicitárias inovam no Dia dos Namorados',
    descricao: 'Marcas apostam em diversidade e inclusão.',
    data: '2024-06-11',
    fonte: 'Meio & Mensagem',
    texto: 'Campanhas deste ano destacam diferentes formas de amor e afeto.',
    empresas_citadas: ['Natura', 'O Boticário'],
    sentimento: 'positivo',
    assuntos: ['publicidade', 'diversidade', 'inclusão'],
    impressoes: 4000,
    valoracao: 8000.00
  },
  {
    id: 6,
    titulo: 'Pesquisa revela presentes mais desejados no Dia dos Namorados',
    descricao: 'Perfumes, flores e jantares lideram a lista.',
    data: '2024-06-10',
    fonte: 'G1',
    texto: 'Levantamento mostra as preferências dos consumidores para a data.',
    empresas_citadas: [],
    sentimento: 'neutro',
    assuntos: ['pesquisa', 'presentes', 'consumo'],
    impressoes: 3000,
    valoracao: 5000.00
  },
  {
    id: 7,
    titulo: 'Aplicativos de namoro registram aumento de usuários',
    descricao: 'Plataformas digitais ganham destaque na busca por relacionamentos.',
    data: '2024-06-09',
    fonte: 'TechTudo',
    texto: 'O uso de apps de namoro cresce próximo ao Dia dos Namorados.',
    empresas_citadas: ['Tinder', 'Bumble'],
    sentimento: 'positivo',
    assuntos: ['aplicativos', 'namoro', 'tecnologia'],
    impressoes: 6000,
    valoracao: 10000.00
  },
  {
    id: 8,
    titulo: 'Hotéis oferecem pacotes especiais para casais',
    descricao: 'Hospedagens criam experiências românticas.',
    data: '2024-06-08',
    fonte: 'Veja',
    texto: 'Hotéis de luxo e pousadas investem em pacotes exclusivos para a data.',
    empresas_citadas: ['Hotel Lux'],
    sentimento: 'positivo',
    assuntos: ['hotéis', 'turismo', 'romance'],
    impressoes: 2000,
    valoracao: 4000.00
  },
  {
    id: 9,
    titulo: 'Dia dos Namorados movimenta o setor de chocolates',
    descricao: 'Vendas aumentam em todo o país.',
    data: '2024-06-07',
    fonte: 'Valor Econômico',
    texto: 'Indústrias de chocolate comemoram alta nas vendas para a data.',
    empresas_citadas: ['Cacau Show', 'Kopenhagen'],
    sentimento: 'positivo',
    assuntos: ['chocolate', 'indústria', 'vendas'],
    impressoes: 3500,
    valoracao: 6000.00
  },
  {
    id: 10,
    titulo: 'Influenciadores digitais lançam campanhas para o Dia dos Namorados',
    descricao: 'Ações de marketing digital ganham força.',
    data: '2024-06-06',
    fonte: 'Exame',
    texto: 'Influenciadores promovem marcas e produtos voltados para casais.',
    empresas_citadas: ['Instagram'],
    sentimento: 'positivo',
    assuntos: ['influenciadores', 'marketing digital', 'campanhas'],
    impressoes: 2500,
    valoracao: 4500.00
  },

  // Energia Nuclear
  {
    id: 11,
    titulo: 'Especialistas debatem futuro da energia nuclear no Brasil',
    descricao: 'Evento reúne autoridades e pesquisadores para discutir expansão da matriz energética.',
    data: '2024-06-10',
    fonte: 'O Globo',
    texto: 'O uso da energia nuclear voltou ao centro do debate nacional, com especialistas apontando desafios e oportunidades para o setor.',
    empresas_citadas: ['Eletronuclear'],
    sentimento: 'neutro',
    assuntos: ['energia', 'meio ambiente', 'política energética'],
    impressoes: 9000,
    valoracao: 20000.00
  },
  {
    id: 12,
    titulo: 'Angra 3 recebe novos investimentos',
    descricao: 'Governo anuncia aporte para conclusão da usina nuclear.',
    data: '2024-06-09',
    fonte: 'Estadão',
    texto: 'A usina de Angra 3 deve ser concluída até 2026, segundo autoridades.',
    empresas_citadas: ['Eletronuclear'],
    sentimento: 'positivo',
    assuntos: ['usina', 'investimento', 'energia nuclear'],
    impressoes: 7000,
    valoracao: 15000.00
  },
  {
    id: 13,
    titulo: 'Pesquisadores desenvolvem tecnologia para resíduos nucleares',
    descricao: 'Nova técnica promete maior segurança no armazenamento.',
    data: '2024-06-08',
    fonte: 'G1',
    texto: 'A inovação pode reduzir riscos ambientais associados ao setor.',
    empresas_citadas: ['CNEN'],
    sentimento: 'positivo',
    assuntos: ['tecnologia', 'resíduos', 'segurança'],
    impressoes: 4000,
    valoracao: 8000.00
  },
  {
    id: 14,
    titulo: 'Energia nuclear e o impacto ambiental',
    descricao: 'Especialistas divergem sobre riscos e benefícios.',
    data: '2024-06-07',
    fonte: 'Folha de S.Paulo',
    texto: 'O debate sobre energia nuclear envolve questões ambientais e econômicas.',
    empresas_citadas: [],
    sentimento: 'neutro',
    assuntos: ['impacto ambiental', 'debate', 'energia'],
    impressoes: 3000,
    valoracao: 6000.00
  },
  {
    id: 15,
    titulo: 'Brasil pode ampliar uso de energia nuclear',
    descricao: 'Estudo aponta potencial de crescimento do setor.',
    data: '2024-06-06',
    fonte: 'Valor Econômico',
    texto: 'O país tem potencial para dobrar a capacidade instalada de energia nuclear.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['crescimento', 'potencial', 'energia nuclear'],
    impressoes: 3500,
    valoracao: 7000.00
  },
  {
    id: 16,
    titulo: 'Energia nuclear no mundo: tendências e desafios',
    descricao: 'Relatório internacional destaca avanços tecnológicos.',
    data: '2024-06-05',
    fonte: 'BBC Brasil',
    texto: 'O setor nuclear global passa por transformações importantes.',
    empresas_citadas: ['IAEA'],
    sentimento: 'positivo',
    assuntos: ['tendências', 'tecnologia', 'internacional'],
    impressoes: 2000,
    valoracao: 4000.00
  },
  {
    id: 17,
    titulo: 'Energia nuclear e fontes renováveis: aliados ou rivais?',
    descricao: 'Especialistas discutem integração das matrizes.',
    data: '2024-06-04',
    fonte: 'O Globo',
    texto: 'A relação entre energia nuclear e renováveis é tema de debate.',
    empresas_citadas: [],
    sentimento: 'neutro',
    assuntos: ['renováveis', 'integração', 'energia'],
    impressoes: 2500,
    valoracao: 5000.00
  },
  {
    id: 18,
    titulo: 'Mercado de trabalho na área nuclear cresce',
    descricao: 'Setor oferece novas oportunidades para engenheiros.',
    data: '2024-06-03',
    fonte: 'Estadão',
    texto: 'A demanda por profissionais especializados aumenta com novos projetos.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['mercado de trabalho', 'engenharia', 'nuclear'],
    impressoes: 1500,
    valoracao: 3000.00
  },
  {
    id: 19,
    titulo: 'Energia nuclear e segurança nacional',
    descricao: 'Autoridades discutem papel estratégico do setor.',
    data: '2024-06-02',
    fonte: 'G1',
    texto: 'A energia nuclear é considerada estratégica para a segurança do país.',
    empresas_citadas: ['Ministério de Minas e Energia'],
    sentimento: 'positivo',
    assuntos: ['segurança', 'estratégia', 'governo'],
    impressoes: 1000,
    valoracao: 2000.00
  },
  {
    id: 20,
    titulo: 'Energia nuclear: mitos e verdades',
    descricao: 'Especialistas esclarecem dúvidas frequentes.',
    data: '2024-06-01',
    fonte: 'Veja',
    texto: 'O setor nuclear ainda é cercado de mitos e desinformação.',
    empresas_citadas: [],
    sentimento: 'neutro',
    assuntos: ['mitos', 'informação', 'energia nuclear'],
    impressoes: 1200,
    valoracao: 2500.00
  },

  // Papa Leão XIV
  {
    id: 21,
    titulo: 'Papa Leão XIV faz visita histórica à América Latina',
    descricao: 'Pontífice realiza encontros com líderes religiosos e políticos em viagem inédita.',
    data: '2024-06-08',
    fonte: 'Folha de S.Paulo',
    texto: 'Em sua primeira visita à América Latina, Papa Leão XIV destacou a importância do diálogo inter-religioso e da paz.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['religião', 'paz', 'América Latina'],
    impressoes: 8000,
    valoracao: 18000.00
  },
  {
    id: 22,
    titulo: 'Papa Leão XIV discursa sobre meio ambiente',
    descricao: 'Pontífice defende preservação ambiental em evento internacional.',
    data: '2024-06-07',
    fonte: 'O Globo',
    texto: 'O Papa ressaltou a importância do cuidado com a criação.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['meio ambiente', 'discurso', 'igreja'],
    impressoes: 6000,
    valoracao: 12000.00
  },
  {
    id: 23,
    titulo: 'Papa Leão XIV encontra jovens em São Paulo',
    descricao: 'Evento reúne milhares de fiéis.',
    data: '2024-06-06',
    fonte: 'Estadão',
    texto: 'O encontro foi marcado por mensagens de esperança e fé.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['juventude', 'esperança', 'fé'],
    impressoes: 4000,
    valoracao: 8000.00
  },
  {
    id: 24,
    titulo: 'Papa Leão XIV visita hospital infantil',
    descricao: 'Pontífice leva mensagem de conforto a crianças e famílias.',
    data: '2024-06-05',
    fonte: 'G1',
    texto: 'A visita emocionou pacientes e profissionais de saúde.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['saúde', 'crianças', 'solidariedade'],
    impressoes: 3000,
    valoracao: 5000.00
  },
  {
    id: 25,
    titulo: 'Papa Leão XIV celebra missa campal',
    descricao: 'Celebração reúne multidão em praça pública.',
    data: '2024-06-04',
    fonte: 'Folha de S.Paulo',
    texto: 'A missa foi marcada por mensagens de paz e união.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['missa', 'paz', 'união'],
    impressoes: 2000,
    valoracao: 4000.00
  },
  {
    id: 26,
    titulo: 'Papa Leão XIV se reúne com líderes indígenas',
    descricao: 'Pontífice ouve demandas e apoia causas sociais.',
    data: '2024-06-03',
    fonte: 'O Globo',
    texto: 'O Papa reforçou o compromisso da Igreja com os povos originários.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['indígenas', 'causas sociais', 'igreja'],
    impressoes: 1500,
    valoracao: 3000.00
  },
  {
    id: 27,
    titulo: 'Papa Leão XIV visita abrigo de refugiados',
    descricao: 'Pontífice leva solidariedade a famílias deslocadas.',
    data: '2024-06-02',
    fonte: 'Estadão',
    texto: 'A visita destacou a importância da acolhida e do respeito.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['refugiados', 'solidariedade', 'acolhida'],
    impressoes: 1000,
    valoracao: 2000.00
  },
  {
    id: 28,
    titulo: 'Papa Leão XIV participa de encontro ecumênico',
    descricao: 'Evento reúne representantes de diferentes religiões.',
    data: '2024-06-01',
    fonte: 'G1',
    texto: 'O Papa defendeu o diálogo e a tolerância entre os povos.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['ecumenismo', 'diálogo', 'tolerância'],
    impressoes: 1200,
    valoracao: 2500.00
  },
  {
    id: 29,
    titulo: 'Papa Leão XIV concede entrevista exclusiva',
    descricao: 'Pontífice fala sobre desafios da Igreja no século XXI.',
    data: '2024-05-31',
    fonte: 'Veja',
    texto: 'O Papa abordou temas como juventude, tecnologia e fé.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['entrevista', 'juventude', 'tecnologia'],
    impressoes: 800,
    valoracao: 1500.00
  },
  {
    id: 30,
    titulo: 'Papa Leão XIV lança campanha de solidariedade',
    descricao: 'Iniciativa arrecada fundos para projetos sociais.',
    data: '2024-05-30',
    fonte: 'Exame',
    texto: 'A campanha visa apoiar comunidades carentes em vários países.',
    empresas_citadas: [],
    sentimento: 'positivo',
    assuntos: ['campanha', 'solidariedade', 'projetos sociais'],
    impressoes: 600,
    valoracao: 1200.00
  }
]; 